import assert from 'node:assert/strict';
import { planPreferencesFromUrl, planShareUrl, planShareText, sharePlan } from '../js/plan-share.js';
import { renderPlanPreview } from '../js/views/planner.js';
const place = { name: 'Ottawa & surroundings', latitude: 45.42, longitude: -75.7 };
const prefs = { activity: 'walk', duration: 30, timeOfDay: 'daylight' };
const url = planShareUrl(place, prefs);
assert.deepEqual(planPreferencesFromUrl(url), prefs, 'a shared planning link restores all choices');
assert.equal(new URL(url).searchParams.get('name'), place.name);
assert.equal(new URL(url).searchParams.has('start'), false, 'old time windows are not restored');
assert.equal(planPreferencesFromUrl('https://www.weatherview.cloud/?activity=walk'), null);
assert.equal(planPreferencesFromUrl('https://www.weatherview.cloud/?view=plan&activity=bad&duration=42'), null);
assert.deepEqual(planPreferencesFromUrl('https://www.weatherview.cloud/?view=plan&activity=walk', { duration: 90, timeOfDay: 'night' }), { activity:'walk',duration:90,timeOfDay:'night' });
const vm = { place, series: [], days: [], planNow: '2026-10-10T12:00', units: { temp:'c',wind:'kmh',clock:'12' }, timezone:'America/Toronto', planPreferences:prefs };
assert.match(renderPlanPreview(vm), /unavailable|No full window/);
assert.doesNotMatch(renderPlanPreview(vm), /planning-time/);
const plan = { activity: { label:'Walk the dog' }, preferences:prefs };
const window = { start:'2026-10-10T23:00',end:'2026-10-11T01:00',minFeels:10,maxFeels:10,maxRainChance:20,maxWind:8 };
assert.match(planShareText(vm,plan,window), /America\/Toronto/);
assert.match(planShareText(vm,plan,window), /Forecast checked/);
assert.match(planShareText(vm,plan,window), /updated suggestions/);
Object.defineProperty(globalThis,'location',{ value:{origin:'https://www.weatherview.cloud'},configurable:true });
Object.defineProperty(globalThis,'navigator',{ value:{ share: async () => { const error=new Error('cancelled');error.name='AbortError';throw error; } },configurable:true });
assert.equal(await sharePlan(vm,plan,window), null, 'cancelled shares do not count as conversions');
let payload;
globalThis.navigator.share=async value => {payload=value;};
assert.equal(await sharePlan(vm,plan,window),'native');
assert.deepEqual(planPreferencesFromUrl(payload.url),prefs);
console.log('Planning links, empty states and share outcomes: passed');
